In [2]:
# DATA CLEANING AND PROCESSING

# data set
# 1. Dataset Imported using pandas
import pandas as pd

data = {
    "Customer_ID": [101, 102, 103, 104, 105, 105],
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Neha", "Neha"],
    "Age": [25, 30, None, 28, 35, 35],
    "City": ["Pune", "Mumbai", "Pune", "Pune", None, "Pune"],
    "Purchase_Amount": [5000, 7500, 3000, None, 9000, 9000]
}

df = pd.DataFrame(data)

df

   Customer_ID   Name   Age    City  Purchase_Amount
0          101   Amit  25.0    Pune           5000.0
1          102  Priya  30.0  Mumbai           7500.0
2          103  Rahul   NaN    Pune           3000.0
3          104  Sneha  28.0    Pune              NaN
4          105   Neha  35.0     NaN           9000.0
5          105   Neha  35.0    Pune           9000.0

In [3]:
# 2. Dataset Structure Inspected
# dataset  basic information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      6 non-null      int64
 1   Name             6 non-null      str
 2   Age              5 non-null      float64
 3   City             5 non-null      str
 4   Purchase_Amount  5 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 372.0 bytes

In [4]:
df.shape

(6, 5)

In [5]:
df.head()

   Customer_ID   Name   Age    City  Purchase_Amount
0          101   Amit  25.0    Pune           5000.0
1          102  Priya  30.0  Mumbai           7500.0
2          103  Rahul   NaN    Pune           3000.0
3          104  Sneha  28.0    Pune              NaN
4          105   Neha  35.0     NaN           9000.0

In [6]:
# 3. missing values Identified

df.isnull().sum()

Customer_ID        0
Name               0
Age                1
City               1
Purchase_Amount    1
dtype: int64

In [7]:
# 4. Duplicates Records Identified
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

Customer_ID        0
Name               0
Age                1
City               1
Purchase_Amount    1
dtype: int64

In [9]:
# 6.Missing values Handled

# missing value age 
df["Age"]=df["Age"].fillna(df["Age"].median())
df

   Customer_ID   Name   Age    City  Purchase_Amount
0          101   Amit  25.0    Pune           5000.0
1          102  Priya  30.0  Mumbai           7500.0
2          103  Rahul  30.0    Pune           3000.0
3          104  Sneha  28.0    Pune              NaN
4          105   Neha  35.0     NaN           9000.0
5          105   Neha  35.0    Pune           9000.0

In [10]:
# missing value city

df["City"] = df["City"].fillna(df["City"].mode()[0])
df

   Customer_ID   Name   Age    City  Purchase_Amount
0          101   Amit  25.0    Pune           5000.0
1          102  Priya  30.0  Mumbai           7500.0
2          103  Rahul  30.0    Pune           3000.0
3          104  Sneha  28.0    Pune              NaN
4          105   Neha  35.0    Pune           9000.0
5          105   Neha  35.0    Pune           9000.0

In [11]:
# Purchase Amount

df["Purchase_Amount"] = df["Purchase_Amount"].fillna(df["Purchase_Amount"].median())
df

   Customer_ID   Name   Age    City  Purchase_Amount
0          101   Amit  25.0    Pune           5000.0
1          102  Priya  30.0  Mumbai           7500.0
2          103  Rahul  30.0    Pune           3000.0
3          104  Sneha  28.0    Pune           7500.0
4          105   Neha  35.0    Pune           9000.0
5          105   Neha  35.0    Pune           9000.0

In [12]:
# check missing vale
df.isnull().sum()

Customer_ID        0
Name               0
Age                0
City               0
Purchase_Amount    0
dtype: int64

In [13]:
# 7.Data Types checked

df.dtypes

Customer_ID          int64
Name                   str
Age                float64
City                   str
Purchase_Amount    float64
dtype: object

In [19]:
# check data

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      6 non-null      int64
 1   Name             6 non-null      str
 2   Age              6 non-null      float64
 3   City             6 non-null      str
 4   Purchase_Amount  6 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 372.0 bytes

In [20]:
# 8. cleaned dataset prepared
df.isnull().sum()

Customer_ID        0
Name               0
Age                0
City               0
Purchase_Amount    0
dtype: int64

In [21]:
df

   Customer_ID   Name   Age    City  Purchase_Amount
0          101   Amit  25.0    Pune           5000.0
1          102  Priya  30.0  Mumbai           7500.0
2          103  Rahul  30.0    Pune           3000.0
3          104  Sneha  28.0    Pune           7500.0
4          105   Neha  35.0    Pune           9000.0
5          105   Neha  35.0    Pune           9000.0

In [22]:
# 9. cleaned CSV Explorted

df.to_csv("cleaned_customer_sales.csv", index=False)

In [23]:
# check the file ready 

import os

os.path.exists("cleaned_customer_sales.csv")

True

In [24]:
# check the CSV file
os.getcwd()

'C:\\Users\\komal chavan'

In [ ]:
# 10. Conclusion
The dataset was successfully cleaned and preprocessed by handling missing values, removing duplicate records, checking data types, and preparing the dataset for further analysis.